services:
  gateway:
    build:
      dockerfile: Dockerfile
      context: src/gateway
    image: mamre32/gateway:latest
    ports:
      - "8080:8080"
  bonus:
    build:
      dockerfile: Dockerfile
      context: src/bonus
    image: mamre32/bonus:latest
    ports:
      - "8050:8050"
    environment:
      DATABASE_URL: "postgresql://program:program@postgres:5432/privileges"
    depends_on:
      postgres:
        condition: service_healthy
  flight:
    build:
      dockerfile: Dockerfile
      context: src/flight
    image: mamre32/flight:latest
    ports:
      - "8060:8060"
    environment:
      DATABASE_URL: "postgresql://program:program@postgres:5432/flights"
    depends_on:
      postgres:
        condition: service_healthy
  ticket:
    build:
      dockerfile: Dockerfile
      context: src/ticket
    image: mamre32/ticket:latest
    ports:
      - "8070:8070"
    environment:
      DATABASE_URL: "postgresql://program:program@postgres:5432/tickets"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U program -d loyalties"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"


volumes:
  db-data:
