serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1    # Минимальное количество подов
  maxReplicas: 10   # Максимальное количество подов  
  targetCPUUtilizationPercentage: 80  # Масштабировать при 80% CPU

service:
  type: ClusterIP
  name: gateway
  port: 8080

image:
  repository: "mamre32/gateway"
  pullPolicy: Always
  tag: "latest"

ingress:
  host: "rsoi-lab.ru"

data:
  DATABASE_URL: "postgresql://program:test@postgresql.default.svc.cluster.local:5432/tickets"
