serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  name: bonus
  port: 8050

autoscaling:
  enabled: true
  minReplicas: 1    # Минимальное количество подов
  maxReplicas: 10   # Максимальное количество подов  
  targetCPUUtilizationPercentage: 80  # Масштабировать при 80% CPU

image:
  repository: "mamre32/bonus"
  pullPolicy: Always
  tag: "latest"

ingress:
  host: "rsoi-lab.ru"

data:
  DATABASE_URL: "postgresql://program:test@postgresql.default.svc.cluster.local:5432/bonus"