replicaCount: 1

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  name: bonus
  port: 8050

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

image:
  repository: "mamre32/bonus"
  pullPolicy: Always
  tag: "latest"

ingress:
  host: "rsoi-lab.ru"

data:
  DATABASE_URL: "postgresql://program:test@postgresql.default.svc.cluster.local:5432/bonus"