serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  name: flight
  port: 8060

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

image:
  repository: "mamre32/flight"
  pullPolicy: Always
  tag: "latest"

ingress:
  host: "rsoi-lab.ru"

data:
  DATABASE_URL: "postgresql://program:test@postgresql.default.svc.cluster.local:5432/flights"